use crate::span::Span;

#[derive(Debug, Clone)]
pub struct Error {
    pub span: Span,
    pub msg: String,
    /// An optional secondary location + label (diagnostics-standard.md C3):
    /// "first call here", "generated by `[derive(Wire)]` on `Point`". One,
    /// not a list — diagnostics stay terse. Rendered as an ariadne sub-label
    /// by the CLI and as related information by the language server.
    pub note: Option<(Span, String)>,
}
