//! The toolchain's embedded `std` — how an installed `vilan` finds its
//! standard library (proposal/releases.md §3).
//!
//! The compiler's std pipeline is filesystem-shaped end to end (layer probing,
//! module listing, `macro_std` beside `std`, manifests), so rather than teach
//! the loader a virtual filesystem, the binary carries the `std` and
//! `macro_std` package trees as data ([`FILES`], generated by `build.rs`) and
//! [`materialize`]s them once into a real directory:
//! `~/.vilan/std-cache/<CONTENT_HASH>/`. The loader then reads ordinary files,
//! and editor go-to-definition into std lands on ordinary files.
//!
//! The cache directory is keyed by [`CONTENT_HASH`], so a rebuilt binary with
//! a different std materializes fresh — the cache can never be stale — and an
//! existing directory is complete by construction: the tree is written to a
//! temporary sibling and atomically renamed into place.

use std::fs;
use std::path::{Path, PathBuf};

include!(concat!(env!("OUT_DIR"), "/embedded_std.rs"));

/// Materializes the embedded toolchain into the default cache
/// (`~/.vilan/std-cache`, or the system temp directory when no home is
/// available) and returns the `std` **package directory** within it — the
/// value `resolve_std` expects. Cheap after the first call: an existing cache
/// entry is returned without touching its contents.
pub fn materialize() -> Result<PathBuf, String> {
    materialize_into(&default_cache_root())
}

/// The default materialization cache root: `~/.vilan/std-cache`, or the system
/// temp directory when no home is available. Shared by [`materialize`] and the
/// upgrade command's cache pruning.
pub fn default_cache_root() -> PathBuf {
    home_dir()
        .map(|home| home.join(".vilan").join("std-cache"))
        .unwrap_or_else(|| std::env::temp_dir().join("vilan-std-cache"))
}

/// Remove cache entries (content-hash trees and crashed `.staging-*`
/// leftovers) whose directory mtime — their creation time; entries are never
/// touched after the atomic rename — is older than `max_age`. Returns how many
/// were removed; a missing root or an unremovable entry is not an error.
///
/// The age guard is the concurrency story: an entry younger than `max_age` may
/// belong to a running binary (std files are read lazily during compilation),
/// so it is left alone. In the rare race — a long-running old binary whose
/// entry ages past the guard while an upgrade prunes — the next resolution
/// simply re-materializes: [`materialize_into`] is idempotent and atomic.
pub fn prune_stale(cache_root: &Path, max_age: std::time::Duration) -> usize {
    let Ok(entries) = std::fs::read_dir(cache_root) else {
        return 0;
    };
    let now = std::time::SystemTime::now();
    let mut removed = 0;
    for entry in entries.flatten() {
        let path = entry.path();
        if !path.is_dir() {
            continue;
        }
        let stale = entry
            .metadata()
            .and_then(|metadata| metadata.modified())
            .ok()
            .and_then(|modified| now.duration_since(modified).ok())
            .is_some_and(|age| age > max_age);
        if stale && std::fs::remove_dir_all(&path).is_ok() {
            removed += 1;
        }
    }
    removed
}

/// [`materialize`] into an explicit cache root (the seam tests use).
pub fn materialize_into(cache_root: &Path) -> Result<PathBuf, String> {
    let target = cache_root.join(CONTENT_HASH);
    let std_dir = target.join("std");
    // Complete by construction: only fully-written trees are renamed in.
    if target.is_dir() {
        return Ok(std_dir);
    }

    // Write the whole tree beside the target, then rename it into place —
    // concurrent first runs race benignly (one rename wins, the loser sees the
    // winner's identical tree).
    let staging = cache_root.join(format!(".staging-{}-{}", CONTENT_HASH, std::process::id()));
    let _ = fs::remove_dir_all(&staging);
    for (key, contents) in FILES {
        let path = staging.join(key);
        let parent = path.parent().expect("every embedded file has a parent");
        fs::create_dir_all(parent)
            .map_err(|error| format!("cannot create {}: {error}", parent.display()))?;
        fs::write(&path, contents)
            .map_err(|error| format!("cannot write {}: {error}", path.display()))?;
    }
    match fs::rename(&staging, &target) {
        Ok(()) => Ok(std_dir),
        Err(error) => {
            let _ = fs::remove_dir_all(&staging);
            if target.is_dir() {
                return Ok(std_dir); // lost the race; the winner's tree is identical
            }
            Err(format!(
                "cannot move the std cache into place at {}: {error}",
                target.display()
            ))
        }
    }
}

/// The user's home directory, from the environment. `std::env::home_dir` is
/// avoided for its Windows history; the plain variables are exactly what the
/// install script and shells define.
fn home_dir() -> Option<PathBuf> {
    std::env::var_os("HOME")
        .or_else(|| std::env::var_os("USERPROFILE"))
        .filter(|value| !value.is_empty())
        .map(PathBuf::from)
}
